source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

def development
  pod 'JWT', path: '../../'
end

target 'SherlockHolmes' do
  development
end

target 'SherlockHolmesTests' do
  development
  pod 'Kiwi'
end
